### ISSUE TITLE
Sample does not work with current xamarin-component.exe

### ISSUE THREAD

**Issue by softlion** [xamarin/component-template#2]
Repro: unpack and run the sample pack and command on windows.

```
xpkg/xamarin-component.exe create sample-component-1.0.xam `
    --name="My Awesome Component" `
    --summary="Add a huge amount of awesomeness to your Xamarin apps." `
    --publisher="Awesome Corp, Inc." `
    --website="http://awesomecorp.com/component" `
    --details="Details.md" `
    --license="License.md" `
    --getting-started="GettingStarted.md" `
    --icon="icons/Awesome_128x128.png" `
    --icon="icons/Awesome_512x512.png" `
    --library="ios":"bin/Awesome.iOS.dll" `
    --library="android":"bin/Awesome.Android.dll" `
    --sample="iOS Sample. Demonstrates Awesomeness on iOS.":"samples/Awesome.iOS.sln" `
    --sample="Android Sample. Demonstrates Awesomeness on Android":"samples/Awesome.Android.sln"
```

Result:

```
INFO (create): Creating component files in sample-component-1.0.xam\component
INFO (create):   * [NEW] sample-component-1.0.xam\component\Details.md
INFO (create):   * [NEW] sample-component-1.0.xam\component\GettingStarted.md
INFO (create):   * [NEW] sample-component-1.0.xam\component\License.md
INFO (create):   * [NEW] sample-component-1.0.xam\component\icon-128.png
ERROR (create):  * [FAILED] sample-component-1.0.xam\component\icon-512.png (Object reference not set to an instance of an object.)
```

**Comment by woutercx** [comment]
Mine doesn't work either. 
Repro:
I download the sample component-template (Clone in desktop from the github page), run rake in my local Github repository that I just cloned.

Result:
computer:component-template wouter$ rake --trace

*\* Invoke default (first_time)
*\* Invoke xamarin-component/xamarin-component.exe (first_time)
*\* Execute xamarin-component/xamarin-component.exe
- Downloading xamarin-component...
  mkdir xamarin-component
  curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  100  864k  100  864k    0     0   249k      0  0:00:03  0:00:03 --:--:--  249k
  unzip -o xamarin-component.zip -d xamarin-component
  Archive:  xamarin-component.zip
  warning:  skipped "../" path component(s) in ../../../../../../../lib/mdoc.exe
  inflating: xamarin-component/lib/mdoc.exe  
  warning:  skipped "../" path component(s) in ../../../../../../../lib/monodoc.dll
  inflating: xamarin-component/lib/monodoc.dll  
  inflating: xamarin-component/xamarin-component.exe  
  rake aborted!
  Command failed with status (1): [unzip -o xamarin-component.zip -d xamarin-...]
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils.rb:53:in `block in create_shell_runner'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils.rb:45:in`call'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils.rb:45:in `sh'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils_ext.rb:40:in`sh'
  /Users/wouter/Ontwikkel/component-template/Rakefile:12:in `block in <top (required)>'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:228:in`call'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:228:in `block in execute'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:223:in`each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:223:in `execute'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:166:in`block in invoke_with_call_chain'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:187:in `block in invoke_prerequisites'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:185:in`each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:185:in `invoke_prerequisites'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:165:in`block in invoke_with_call_chain'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task.rb:152:in `invoke'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:143:in`invoke_task'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in top_level'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in`each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:110:in`run_with_threads'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:73:in`block in run'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:70:in`run'
  /usr/bin/rake:37:in `<main>'
  Tasks: TOP => default => xamarin-component/xamarin-component.exe

**Comment by woutercx** [comment]
I troubleshooted by removing the following part from the rake file:

file "xamarin-component/xamarin-component.exe" do
        puts "\* Downloading xamarin-component..."
        mkdir "xamarin-component"
        sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
        sh "unzip -o xamarin-component.zip -d xamarin-component"
        sh "rm xamarin-component.zip"
end

Then I executed these commands I just removed by hand:

computer:component-template wouter$ curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  864k  100  864k    0     0   338k      0  0:00:02  0:00:02 --:--:--  338k

computer:component-template wouter$ unzip -o xamarin-component.zip -d xamarin-component

Archive:  xamarin-component.zip
warning:  skipped "../" path component(s) in ../../../../../../../lib/mdoc.exe
  inflating: xamarin-component/lib/mdoc.exe  
warning:  skipped "../" path component(s) in ../../../../../../../lib/monodoc.dll
  inflating: xamarin-component/lib/monodoc.dll  
  inflating: xamarin-component/xamarin-component.exe  

computer:component-template wouter$ rm xamarin-component.zip

Then everything went fine when I ran rake:

computer:component-template wouter$ rake
- Creating awesome-1.0.xam...
  mono xamarin-component/xamarin-component.exe create-manually awesome-1.0.xam \
  --name="My Awesome Component" \
  --summary="Add a huge amount of awesomeness to your Xamarin apps." \
  --publisher="Awesome Corp, Inc." \
  --website="http://awesomecorp.com/component" \
  --details="Details.md" \
  --license="License.md" \
  --getting-started="GettingStarted.md" \
  --icon="icons/awesome_128x128.png" \
  --icon="icons/awesome_512x512.png" \
  --library="ios":"bin/Awesome.iOS.dll" \
  --library="android":"bin/Awesome.Android.dll" \
  --sample="iOS Sample. Demonstrates Awesomeness on iOS.":"samples/Awesome.iOS.sln" \
  --sample="Android Sample. Demonstrates Awesomeness on Android":"samples/Awesome.Android.sln"
- Created awesome-1.0.xam

So the problem is somewhere in the unzipping part. Strange, because it seems to execute well when I do it by hand.

**Comment by woutercx** [comment]
I think I nailed it.
Because of the 2 warnings: 
   warning: skipped "../" path BLA BLA BLA

the unzip command passes this error to rake, which aborts the script.
To solve this, change

sh "unzip -o xamarin-component.zip -d xamarin-component"

to

sh "unzip -o -q xamarin-component.zip -d xamarin-component"

(-q means : quiet mode)

then it works.

**Comment by rafaelcgo** [comment]
In case anyone arrives here looking for a way to prevent `sh "unzip"` from failing and -q is not enough...

Options:
1

``` ruby
sh "unzip zipfile.zip" do
  # Ignore errors
end
```

2

``` ruby
sh "unzip zipfile; true"
```

From: http://www.rake.build/fascicles/004-ignore-failed-tasks.html
